### ISSUE TITLE
Difference between mikesplain/openvas & mikesplain/openvas:9

### ISSUE THREAD

**Issue by Fredus69** [mikesplain/openvas-docker#153]
Hello,

In the "Usage" section, there is this information :

"
# latest (9)
docker run -d -p 443:443 --name openvas mikesplain/openvas
# 9
docker run -d -p 443:443 --name openvas mikesplain/openvas:9
"

What is the difference between those 2 commands :
=> docker run -d -p 443:443 --name openvas mikesplain/openvas
and
=> docker run -d -p 443:443 --name openvas mikesplain/openvas:9

I tried both and each one starts a container with Openvas 9, and i saw no difference.
Sorry if my question is odd, i am newby with Docker.

Thanks for your help,

Best Regards,

Fred

**Comment by mikesplain** [comment]
Hi @Fredus69, there actually is no difference between them. Originally we had openvas version 8 and 9 so we would point `mikesplain/openvas` (also known as `mikesplain/openvas:latest`) at either 8 or 9 depending on the status of the openvas project. Since we have deprecated v9 support, we simply point it at 9.  Hope this helps!

**Comment by mikesplain** [comment]
Please reopen if you have any other questions
