### ISSUE TITLE
setting password via environment variable does not work

### ISSUE THREAD

**Issue by hacker-h** [mikesplain/openvas-docker#182]
Using the given example run command to set the admin password via environmental variable fails:
docker run -d -p 443:443 -e OV_PASSWORD=securepassword41 --name openvas mikesplain/openvas

Apparently the variable OV_PASSWORD is not read successfully, there might be a bug in the file "start".

**Comment by yippeykeiyay** [comment]
Yep, same issue here.

**Comment by Sopamo** [comment]
Until the issue is fixed you can set the password manually by executing

`openvasmd --user=admin --new-password=your_secure_password`

**Comment by yippeykeiyay** [comment]
@Sopamo thank you!

**Comment by fabionitto** [comment]
Actually, the password on OV_PASSWORD is set only if the variable SETUPUSER is set.
So setting SETUPUSER=true should do it. 
Only watch out because it takes a while for openvasmd to set the password, since its done only after NVT rebuild process, which takes a while.

On a side note to dev: could admin password be set from OV_PASSWORD variable, before NVT rebuilding?

**Comment by BadFlo** [comment]
Still same issue. in start file, "IF" should be modified to allow password change after first start of container.

**Comment by hacker-h** [comment]
the issue is still present
