### ISSUE TITLE
Feature: reduce image size

### ISSUE THREAD

**Issue by hazcod** [mikesplain/openvas-docker#250]

**Comment by iamjoeker** [comment]
The primary reason that the image is so large is that it contains all the data needed for scanning. IMHO, this is a _good_ thing. Otherwise, it would take significantly longer to spin up a new container as _all_ the data needed for scanning would have to be downloaded. Personally, I prefer for the image to contain the scanning data and be as up to date as possible so that I can launch a container and update definitions in a reasonable amount of time.

**Comment by hazcod** [comment]
Fyi this still uses openvas 9 while 11 is available.

**Comment by iamjoeker** [comment]
> Fyi this still uses openvas 9 while 11 is available.

Correct.

**Comment by turkmenkaan** [comment]
It might be possible to reduce the image size by using a smaller base image than Ubuntu.
